# Train and save model, excluding explicit set of variants.
# Then make predictions. 

##########
# Train 

fname_prefix: "out_model."

enable_train_save: True
exclude_list: "list_to_exclude.txt"
exclUNC: True
exclNM: True

##########
# Test

enable_test: True
include_list: "list_to_exclude.txt"
exclUNC: False
exclNM: False

##########

model_features: 'origammpnnesm'
fname_model_prefix: "save_model_state.rfc.biophys_evol_am_mpnnesm.excl_ambiguous."

##########

##############################

excludeWT: True
VSDonly: False
PDonly: False

featuresCSVList:  ["features_8sik_clean.w_am_mpnn_esm.csv"]
trainLabelsCSV: "kcnq1_all_measurements.csv"

##########
labels:
  - name: iks
    rcut: [0.65, 1.4]
    pvalcut: [0.02,0.05]
    gof: larger
     
  - name: v12
    rcut: [-5,5]
    pvalcut: [0.02,0.05]
    gof: smaller
 
  - name: tau_act
    rcut: [0.7, 1.7]    
    pvalcut: [0.02,0.05]
    gof: smaller
 
  - name: tau_deact
    rcut: [0.75, 1.25]
    pvalcut: [0.02,0.05]
    gof: larger

  - name: cell_surf_exp
    rcut: [65,150]
    pvalcut: null
    gof: larger

  - name: tot_exp
    rcut: [65,150]
    pvalcut: null
    gof: larger

  - name: traffick_eff
    rcut: [65,150]
    pvalcut: null
    gof: larger
